apiVersion: apps/v1
kind: Deployment
metadata:
  name: daybrew-fe
  namespace: daybrew
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 3
  selector:
    matchLabels:
      app: daybrew-fe
  template:
    metadata:
      labels:
        app: daybrew-fe
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: daybrew-fe
          image: ghcr.io/yoon6yo/devbrew-fe:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
